# nginx proxy address - http://172.17.0.1:1337

name: strapi
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: strapi/strapi:latest
    container_name: strapi-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      HOST: ${STRAPI_HOST:-0.0.0.0}
      PORT: ${STRAPI_PORT:-1337}
      APP_KEYS: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      API_TOKEN_SALT: ${APP_SECRET_TOKEN_32:-changeme_api_token_salt_32chars}
      ADMIN_JWT_SECRET: ${APP_JWT_TOKEN:-changeme_admin_jwt_secret_32c}
      TRANSFER_TOKEN_SALT: ${ENCRYPTION_KEY:-changeme_transfer_token_salt32}
      DATABASE_CLIENT: ${DATABASE_CLIENT:-sqlite}
      DATABASE_FILENAME: /data/strapi.db
      CONTAINER_NAME: strapi-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:1337:1337'
    volumes:
      - './volumes/data/strapi:/data'
      - './volumes/config/strapi:/config'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://strapi-app:1337'
      - 'cloudflare.hostname=strapi.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.strapi-app.entrypoints=http'
      - 'traefik.http.routers.strapi-app-secure.tls=true'
      - 'traefik.http.routers.strapi-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.strapi-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.strapi-app.middlewares=strapi-app-https-redirect'
      - 'traefik.http.routers.strapi-app-secure.entrypoints=https'
      - 'traefik.http.routers.strapi-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.strapi-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.strapi-app-secure.service=strapi-app'
      - 'traefik.http.services.strapi-app.loadbalancer.server.port=1337'
    networks:
      - strapi
      - proxy
      - cloudflare

networks:
  strapi:
    name: strapi
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
