# nginx proxy address - http://172.17.0.1:1337

name: strapi
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: strapi/strapi:latest
    container_name: strapi-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      HOST: ${STRAPI_HOST:-0.0.0.0}
      PORT: ${STRAPI_PORT:-1337}
      APP_KEYS: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      API_TOKEN_SALT: ${API_TOKEN_SALT:-changeme_api_token_salt_32chars}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-changeme_admin_jwt_secret_32c}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT:-changeme_transfer_token_salt32}
      DATABASE_CLIENT: ${DATABASE_CLIENT:-sqlite}
      DATABASE_FILENAME: /data/strapi.db
    ports:
      - '172.17.0.1:1337:1337'
    volumes:
      - './volumes/data/strapi:/data'
      - './volumes/config/strapi:/config'
    networks:
      - strapi

networks:
  strapi:
    name: strapi
    external: false
