# nginx proxy address - http://172.17.0.1:1337

name: strapi
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: strapi/strapi:latest
    container_name: strapi-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:1337:1337'
    volumes:
      - './rootfs/data/strapi:/data'
    networks:
      - strapi

networks:
  strapi:
    name: strapi
    external: false
